#!/usr/bin/env node
/**
 * Library integrity check — the mirror half of `npm run check`.
 *
 * A mirror is a mirror: generated by scripts/sync-library.ts, never
 * hand-edited. This validates what a broken sync or a stray edit would
 * silently ship: frontmatter completeness, contentHash (hand-edit
 * detection), ~-relative provenance, collection placement, the deny wall
 * (nothing mirrored may match manifest deny), and a defense-in-depth
 * deny-scan over mirrored bodies. Invoked from check-content.mjs so the
 * PostToolUse hook, the curator gates, and the library-sync gate all get
 * it for free; runnable standalone too.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { pathToFileURL } from "node:url";
import matter from "gray-matter";
import { scanDoc, globToRegExp } from "./lib/deny-scan.mjs";
import { loadManifest, allCollections } from "./lib/manifest.mjs";

export function checkLibrary(root = process.cwd()) {
  const errors = [];
  const warns = [];
  const libDir = path.join(root, "content", "library");
  if (!fs.existsSync(libDir)) return { errors, warns, count: 0 };

  let manifest;
  try {
    manifest = loadManifest(root);
  } catch {
    errors.push("content/library exists but config/library.manifest.json is missing/unreadable");
    return { errors, warns, count: 0 };
  }
  const denyRes = manifest.deny.map(globToRegExp);
  const collectionIds = new Set(allCollections(root, manifest).map((c) => c.id));

  const walk = (dir) =>
    fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
      e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]
    );

  let count = 0;
  for (const file of walk(libDir)) {
    const rel = path.join("content", "library", path.relative(libDir, file));
    if (!file.endsWith(".md")) {
      errors.push(`${rel}: mirrors are .md only (found ${path.extname(file) || "no extension"})`);
      continue;
    }
    count++;
    const { data, content } = matter(fs.readFileSync(file, "utf8"));

    for (const field of ["title", "collection", "source", "sourceMtime", "syncedAt", "contentHash"]) {
      if (!data[field]) errors.push(`${rel}: missing generated frontmatter \`${field}\``);
    }
    if (data.source && !String(data.source).startsWith("~/")) {
      errors.push(`${rel}: source must be ~-relative, got "${data.source}"`);
    }
    if (data.collection && !collectionIds.has(data.collection)) {
      errors.push(`${rel}: collection "${data.collection}" is not in the manifest (or its project lost its repo:)`);
    }
    if (data.collection) {
      const placed = path.dirname(path.relative(libDir, file));
      if (placed !== String(data.collection)) {
        errors.push(`${rel}: filed under "${placed}" but frontmatter says "${data.collection}"`);
      }
    }
    if (data.source && denyRes.some((re) => re.test(String(data.source)))) {
      errors.push(`${rel}: mirrors a DENIED source (${data.source}) — remove it and fix the sync`);
    }
    if (data.contentHash) {
      let body = content.replace(/^\n+/, "");
      if (!body.endsWith("\n")) body += "\n";
      const hash = `sha256:${crypto.createHash("sha256").update(body).digest("hex")}`;
      if (hash !== data.contentHash) {
        errors.push(`${rel}: body doesn't match contentHash — mirrors are never hand-edited; edit the source (${data.source}) and re-run the sync`);
      }
    }
    const scan = scanDoc(content);
    for (const label of scan.hard) {
      errors.push(`${rel}: deny-scan found what looks like a real ${label} in a mirrored body`);
    }
  }
  return { errors, warns, count };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { errors, warns, count } = checkLibrary();
  for (const w of warns) console.warn(`warn  ${w}`);
  if (errors.length) {
    for (const e of errors) console.error(`ERROR ${e}`);
    console.error(`\n${errors.length} library error(s).`);
    process.exit(1);
  }
  console.log(`library ok — ${count} mirrors validated.`);
}
